when:
  event: [push, pull_request]

steps:
  lint:
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup component add rustfmt
      - cargo fmt --all --check
      - cargo clippy --all-features -- --deny clippy::all --deny warnings
