on: [push, pull_request]

name: Continuous integration

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  check:
    name: ${{ matrix.triple.os }} / ${{ matrix.toolchain }}
    needs: [rustfmt, clippy]
    runs-on: ${{ matrix.triple.os }}
    strategy:
      fail-fast: false
      matrix:
        triple:
          - { os: 'ubuntu-latest',  target: 'x86_64-unknown-linux-gnu', cross: false }
          - { os: 'ubuntu-latest',  target: 'i686-unknown-linux-gnu',   cross: true }

          - { os: 'macOS-latest',   target: 'x86_64-apple-darwin',      cross: false }

          # TODO:
          # - { os: 'windows-latest', target: 'x86_64-pc-windows-msvc',   cross: false }
          # TODO: FreeBSD
        toolchain:
          - 1.32.0  # MSRV
          - stable

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install cross
        if: matrix.triple.cross == true
        uses: actions-rs/install@v0.1
        with:
          crate: cross

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.triple.target }}
          use-cross: ${{ matrix.triple.cross }}
